// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwysjimybsxcogkgxquo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eXNqaW15YnN4Y29na2d4cXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjM3NDQsImV4cCI6MjA2MDQzOTc0NH0.qChcaR0fzdZ4V2fbOn4pRhhfhHzStwBZcd_rBU9Jjp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);